### ISSUE TITLE
Last event not update

### ISSUE THREAD

**Issue by dhiogoboza** [rubenochiavone/rastreio-java#1]
Possibly there is a issue with the last event for package with tracking code LB107580877SG. The event is not being returned.

**Comment by rubenochiavone** [comment]
At b3e20b7b159d72da53dc00068272a41dd97ddbb8 I added it to the test suite. Any chance I missed something?

**Comment by dhiogoboza** [comment]
Please check RH117939038TR too.

**Comment by rubenochiavone** [comment]
This tracking code generated a HTML response that didn't have the same pattern as other ones. It was lacking a **strong** node.

Fixed it on `1.0.1` (ba46f953bcba80b5bad5dc695460f81d27b526d6), please check it. :rocket: 

By the way, thank you for the bug report. :pray:

**Comment by dhiogoboza** [comment]
Thanks, this fix solved the issue in my application.
