### ISSUE TITLE
Deprecated java.util.Date

### ISSUE THREAD

**Issue by dhiogoboza** [rubenochiavone/rastreio-java#2]
Is it possible to you replace deprecated java.util.Date by another solution?

**Comment by rubenochiavone** [comment]
I am not sure that `java.util.Date` class is deprecated. A few methods are though.

I wrote a test case that checks `rastreio.TrackObject#getPostedAt()` and `rastreio.TrackObject#getUpdatedAt()` for example. Please take a look:

https://github.com/rubenochiavone/rastreio-java/blob/b3e20b7b159d72da53dc00068272a41dd97ddbb8/src/test/java/rastreio/RastreioTest.java#L116-L118

Before 32166b1679cc1154ea2a2d08db4fc24d8697a2c6,  was not properly setting seconds and milliseconds. Do you have any use case that `java.util.Date` is not enough?

**Comment by dhiogoboza** [comment]
Yes, some methods are deprecated. I believe that using another solution will be better, but ok. I just use `Calendar` as you metioned.

**Comment by dhiogoboza** [comment]
The fix in seconds and nanosecons resolve my issue, thanks.
