### ISSUE TITLE
Details for LB679011587SE

### ISSUE THREAD

**Issue by dhiogoboza** [rubenochiavone/rastreio-java#4]
I believe that the text "Por favor, aguarde" for an event for the tracking code LB679011587SE not is being processed.

**Comment by rubenochiavone** [comment]
I see. Unfortunately, correios official web page responses slightly differ from the ones we get. Here's current response for **LB679011587SE**:

![image](https://user-images.githubusercontent.com/9703203/75504890-7a5d2280-59b8-11ea-8b50-9f85105fee6c.png)

So, there is nothing I could do. :disappointed:

Hope you can understand.

**Comment by dhiogoboza** [comment]
Ok, no problem, thanks.
